
#include "STD_DEFS.H"
#include "COM_TBLS.H"

/*
** This DDL will build a complete DD containing all blocks and parameters 
** DD is stored by default as Release\000000\ffff\ffff.ddo
**
** Filename:	FF_TEST.DDL
** Revision:	1.2
** Date:		2007-10-31
** Std. Lib:	3.2 beta
** DISCLAIMER OF WARRANTIES
**
** THIS DOCUMENT IS PROVIDED ON AN "AS IS" BASIS AND MAY BE SUBJECT TO FUTURE
** ADDITIONS, MODIFICATIONS, OR CORRECTIONS DEPENDING ON THE RESULTS OF FIELD
** TRIAL TESTING.  THE FIELDBUS FOUNDATION(TM) HEREBY DISCLAIMS ALL WARRANTIES
** OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTY OF MERCHANTABILITY
** OR FITNESS FOR A PARTICULAR PURPOSE, FOR THIS DOCUMENT.  IN NO EVENT WILL
** THE FIELDBUS FOUNDATION(TM) BE RESPONSIBLE FOR ANY LOSS OR DAMAGE ARISING
** OUT OF OR RESULTING FROM ANY DEFECT, ERROR OR OMISSION IN THIS DOCUMENT OR
** FROM ANYONE'S USE OF OR RELIANCE ON THIS DOCUMENT.
** DISCLAIMER OF WARRANTIES
**
** MS   AR3343 - added FD params to RB block and views
**
** (c) Fieldbus Foundation(TM) (1994-2007)
*/

	
#define __FF_TEST_DD		0xFFFF
#define __FF_TEST_dev_rev	0xFF
#define __FF_TEST_dd_rev	0xFF

/*
***********************************************************************
Test DD
***********************************************************************
*/

MANUFACTURER 	__FF, 
DEVICE_TYPE 	__FF_TEST_DD, 
DEVICE_REVISION __FF_TEST_dev_rev, 
DD_REVISION 	__FF_TEST_dd_rev

/*
***********************************************************************
IMPORT entire standard library
***********************************************************************
*/
	
IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__STD_PARM,
		DEVICE_REVISION 	__STD_PARM_rel_dev_rev,
		DD_REVISION 		__STD_PARM_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__AI_BLOCK,
		DEVICE_REVISION 	__AI_BLOCK_rel_dev_rev,
		DD_REVISION 		__AI_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__AO_BLOCK,
		DEVICE_REVISION 	__AO_BLOCK_rel_dev_rev,
		DD_REVISION 		__AO_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__DI_BLOCK,
		DEVICE_REVISION 	__DI_BLOCK_rel_dev_rev,
		DD_REVISION 		__DI_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__DO_BLOCK,
		DEVICE_REVISION 	__DO_BLOCK_rel_dev_rev,
		DD_REVISION 		__DO_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__BG_BLOCK,
		DEVICE_REVISION 	__BG_BLOCK_rel_dev_rev,
		DD_REVISION 		__BG_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__ML_BLOCK,
		DEVICE_REVISION 	__ML_BLOCK_rel_dev_rev,
		DD_REVISION 		__ML_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__PD_BLOCK,
		DEVICE_REVISION 	__PD_BLOCK_rel_dev_rev,
		DD_REVISION 		__PD_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__PID_BLOCK,
		DEVICE_REVISION 	__PID_BLOCK_rel_dev_rev,
		DD_REVISION 		__PID_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__RA_BLOCK,
		DEVICE_REVISION 	__RA_BLOCK_rel_dev_rev,
		DD_REVISION 		__RA_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__CS_BLOCK,
		DEVICE_REVISION 	__CS_BLOCK_rel_dev_rev,
		DD_REVISION 		__CS_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__RES_BLOCK,
		DEVICE_REVISION 	__RES_BLOCK_rel_dev_rev,
		DD_REVISION 		__RES_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__STD_XDCR_PARM,
		DEVICE_REVISION 	__STD_XDCR_PARM_beta_dev_rev,
		DD_REVISION 		__STD_XDCR_PARM_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__ADV_POS_BASIC,
		DEVICE_REVISION 	__ADV_POS_BASIC_beta_dev_rev,
		DD_REVISION 		__ADV_POS_BASIC_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__BASIC_POS_BASIC,
		DEVICE_REVISION 	__BASIC_POS_BASIC_beta_dev_rev,
		DD_REVISION 		__BASIC_POS_BASIC_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__DISC_POS_BASIC,
		DEVICE_REVISION 	__DISC_POS_BASIC_beta_dev_rev,
		DD_REVISION 		__DISC_POS_BASIC_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__FLOW_BASIC,
		DEVICE_REVISION 	__FLOW_BASIC_beta_dev_rev,
		DD_REVISION 		__FLOW_BASIC_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__PRESS_BASIC,
		DEVICE_REVISION 	__PRESS_BASIC_rel_dev_rev,
		DD_REVISION 		__PRESS_BASIC_rel_dd_rev
{EVERYTHING;}

IMPORT	MANUFACTURER    __FF,
	DEVICE_TYPE     __PRESS_BASIC2,
	DEVICE_REVISION __PRESS_BASIC2_rel_dev_rev,
	DD_REVISION     __PRESS_BASIC2_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__RADAR_LVL_BASIC,
		DEVICE_REVISION 	__RADAR_LVL_BASIC_beta_dev_rev,
		DD_REVISION 		__RADAR_LVL_BASIC_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__TEMPERATURE_BASIC,
		DEVICE_REVISION 	__TEMPERATURE_BASIC_rel_dev_rev,
		DD_REVISION 		__TEMPERATURE_BASIC_rel_dd_rev
{EVERYTHING;}

IMPORT	MANUFACTURER    __FF,
	DEVICE_TYPE     __TEMPERATURE_BASIC2,
	DEVICE_REVISION __TEMPERATURE_BASIC2_rel_dev_rev,
	DD_REVISION     __TEMPERATURE_BASIC2_rel_dd_rev
{EVERYTHING;}

IMPORT MANUFACTURER			__FF, 
	DEVICE_TYPE			__TEMPERATURE_BASIC_2_SENSOR, 
	DEVICE_REVISION			__TEMPERATURE_BASIC_2_SENSOR_rel_dev_rev, 
	DD_REVISION			__TEMPERATURE_BASIC_2_SENSOR_rel_dd_rev
{EVERYTHING;}

IMPORT	MANUFACTURER    __FF,
	DEVICE_TYPE     __TEMPERATURE_BASIC_2_SENSOR2,
	DEVICE_REVISION __TEMPERATURE_BASIC_2_SENSOR2_rel_dev_rev,
	DD_REVISION     __TEMPERATURE_BASIC_2_SENSOR2_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__STD_MIO_PARM,
		DEVICE_REVISION 	__STD_MIO_PARM_rel_dev_rev,
		DD_REVISION 		__STD_MIO_PARM_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__MDI,
		DEVICE_REVISION 	__MDI_rel_dev_rev,
		DD_REVISION 		__MDI_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__MDO,
		DEVICE_REVISION 	__MDO_rel_dev_rev,
		DD_REVISION 		__MDO_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__MAI,
		DEVICE_REVISION 	__MAI_rel_dev_rev,
		DD_REVISION 		__MAI_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__MAO,
		DEVICE_REVISION 	__MAO_rel_dev_rev,
		DD_REVISION 		__MAO_rel_dd_rev
{EVERYTHING;}

IMPORT MANUFACTURER    __FF,
DEVICE_TYPE     __CUSTOM_CALC_BLOCK,
DEVICE_REVISION __CUSTOM_CALC_BLOCK_rel_dev_rev,
DD_REVISION     __CUSTOM_CALC_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT MANUFACTURER    __FF,
DEVICE_TYPE     __CUSTOM_CONTROL_BLOCK,
DEVICE_REVISION __CUSTOM_CONTROL_BLOCK_rel_dev_rev,
DD_REVISION     __CUSTOM_CONTROL_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT MANUFACTURER    __FF,
DEVICE_TYPE     __CUSTOM_INPUT_BLOCK,
DEVICE_REVISION __CUSTOM_INPUT_BLOCK_rel_dev_rev,
DD_REVISION     __CUSTOM_INPUT_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT MANUFACTURER    __FF,
DEVICE_TYPE     __CUSTOM_OUTPUT_BLOCK,
DEVICE_REVISION __CUSTOM_OUTPUT_BLOCK_rel_dev_rev,
DD_REVISION     __CUSTOM_OUTPUT_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT MANUFACTURER    __FF,
DEVICE_TYPE     __COMPLEX_TB,
DEVICE_REVISION __COMPLEX_TB_rel_dev_rev,
DD_REVISION     __COMPLEX_TB_rel_dd_rev
{EVERYTHING;}

IMPORT MANUFACTURER    __FF,
DEVICE_TYPE     __POS_ANALOG,
DEVICE_REVISION __POS_ANALOG_rel_dev_rev,
DD_REVISION     __POS_ANALOG_rel_dd_rev
{EVERYTHING;}

IMPORT MANUFACTURER    __FF,
DEVICE_TYPE     __POS_DISCRETE,
DEVICE_REVISION __POS_DISCRETE_rel_dev_rev,
DD_REVISION     __POS_DISCRETE_rel_dd_rev
{EVERYTHING;}

IMPORT MANUFACTURER    __FF,
DEVICE_TYPE     __POS_ANALOG_DISCRETE,
DEVICE_REVISION __POS_ANALOG_DISCRETE_rel_dev_rev,
DD_REVISION     __POS_ANALOG_DISCRETE_rel_dd_rev
{
    EVERYTHING;

    REDEFINITIONS
    {
        BLOCK __pos_a_d_xdcr_block
        {
            PARAMETERS
            {
            	__POS_GROUP_E_PARAMS
            	__POS_GROUP_F_PARAMS
            	__POS_GROUP_G_PARAMS
            	__POS_GROUP_H_PARAMS
            	__POS_GROUP_I_PARAMS
            	__POS_GROUP_J_PARAMS
            	__POS_GROUP_K_PARAMS
            	__POS_GROUP_L_PARAMS
            }
        }
        
        VARIABLE_LIST   __pos_a_d_xdcr_view_1
	{
		MEMBERS
	        {
	        	ADD VL_VST_COMMAND,		    PARAM.VST_COMMAND ;
			ADD VL_VST_MODE,		    PARAM.VST_MODE ;
			ADD VL_VST_RESULT,		    PARAM.VST_RESULT ;
			ADD VL_VST_DETAILED_RESULT,	PARAM.VST_DETAILED_RESULT ;
			ADD VL_TORQUE,			    PARAM.TORQUE ;
		}    
	}
	    
	VARIABLE_LIST   __pos_a_d_xdcr_view_2
	{
		MEMBERS
	    	{
	    		ADD VL_VST_PAUSE,		PARAM.VST_PAUSE ;
		}    
	}
	                
	VARIABLE_LIST   __pos_a_d_xdcr_view_3
	{
		MEMBERS
	        {
	         	ADD VL_VST_COMMAND,		    PARAM.VST_COMMAND ;
			ADD VL_VST_MODE,		    PARAM.VST_MODE ;
			ADD VL_VST_RESULT,		    PARAM.VST_RESULT ;
			ADD VL_VST_DETAILED_RESULT,	PARAM.VST_DETAILED_RESULT ;
			ADD VL_CLOSED_POS_SHIFT,	PARAM.CLOSED_POS_SHIFT ;
			ADD VL_FRICTION,		    PARAM.FRICTION ;
			ADD VL_HYSTERISIS,		    PARAM.HYSTERISIS ;
			ADD VL_XD_COMMAND_FLAGS,	PARAM.XD_COMMAND_FLAGS ;
			ADD VL_TORQUE,			    PARAM.TORQUE ;
			ADD VL_PRESSURE_PORT_A,		PARAM.PRESSURE_PORT_A ;
			ADD VL_PRESSURE_PORT_B,		PARAM.PRESSURE_PORT_B ;
			ADD VL_PRESSURE_SUPPLY,	PARAM.PRESSURE_SUPPLY ;
			ADD VL_CHARACTERIZATION,	PARAM.CHARACTERIZATION ;
			ADD VL_STROKE_TIME_CLOSE_LIM,	PARAM.STROKE_TIME_CLOSE_LIM ;
			ADD VL_STROKE_TIME_OPEN_LIM,	PARAM.STROKE_TIME_OPEN_LIM ;
			ADD VL_TRAVEL_ACCUM_LIM,	PARAM.TRAVEL_ACCUM_LIM ;
			ADD VL_TRAVEL_ACCUM_UNITS,	PARAM.TRAVEL_ACCUM_UNITS ;
			ADD VL_INTERNAL_TEMP,		PARAM.INTERNAL_TEMP ;
			ADD VL_INTERNAL_TEMP_MIN,	PARAM.INTERNAL_TEMP_MIN ;
			ADD VL_INTERNAL_TEMP_MAX,	PARAM.INTERNAL_TEMP_MAX ;
		}    
	}
	    	    
	VARIABLE_LIST   __pos_a_d_xdcr_view_4
	{
		MEMBERS
	       	{
	       	 	ADD VL_CLOSED_POS_DEADBAND,		PARAM.CLOSED_POS_DEADBAND ;
			ADD VL_CUSTOM_CURVE_DESCRIPTION,	PARAM.CUSTOM_CURVE_DESCRIPTION ;
			ADD VL_CUSTOM_CURVE_XY,			PARAM.CUSTOM_CURVE_XY ;
			ADD VL_CUSTOM_CURVE_XY_FLOAT,		PARAM.CUSTOM_CURVE_XY_FLOAT ;
			ADD VL_CYCLE_CNTR_DEADBAND,		PARAM.CYCLE_CNTR_DEADBAND ;
			ADD VL_FRICTION_UNITS,			PARAM.FRICTION_UNITS ;
			ADD VL_POS_DEADBAND,			PARAM.POS_DEADBAND ;
			ADD VL_STROKE_TIME_CLOSED,		PARAM.STROKE_TIME_CLOSED ;
			ADD VL_STROKE_TIME_OPEN,		PARAM.STROKE_TIME_OPEN ;
			ADD VL_TRAVEL_ACCUM_DEADBAND,		PARAM.TRAVEL_ACCUM_DEADBAND ;
			ADD VL_TRIP_TIMEOUT,			PARAM.TRIP_TIMEOUT ;
			ADD VL_CYCLE_CNTR_LIM,			PARAM.CYCLE_CNTR_LIM ;
			ADD VL_PST_BREAKOUT_TIME,		PARAM.PST_BREAKOUT_TIME ;
			ADD VL_PST_BREAKOUT_TIMEOUT,		PARAM.PST_BREAKOUT_TIMEOUT ;
			ADD VL_PST_INITIAL_START_TIME,		PARAM.PST_INITIAL_START_TIME ;
			ADD VL_PST_INTERVAL,			PARAM.PST_INTERVAL ;
			ADD VL_PST_OPTIONS,			PARAM.PST_OPTIONS ;
			ADD VL_PST_RAMP_RATE,			PARAM.PST_RAMP_RATE ;
			ADD VL_PST_STRK_TRAV,			PARAM.PST_STRK_TRAV ;
			ADD VL_PST_STRK_TRAV_TIMEOUT,		PARAM.PST_STRK_TRAV_TIMEOUT ;
			ADD VL_PST_COMPLETION_TIMEOUT,		PARAM.PST_COMPLETION_TIMEOUT ;
			ADD VL_TORQUE_UNITS,			PARAM.TORQUE_UNITS ;
			ADD VL_FST_BREAKOUT_TIME,		PARAM.FST_BREAKOUT_TIME ;
			ADD VL_FST_BREAKOUT_TIMEOUT,		PARAM.FST_BREAKOUT_TIMEOUT ;
			ADD VL_FST_RAMP_RATE,			PARAM.FST_RAMP_RATE ;
			ADD VL_FST_STRK_TRAV_TIMEOUT,		PARAM.FST_STRK_TRAV_TIMEOUT ;
			ADD VL_FST_COMPLETION_TIMEOUT,		PARAM.FST_COMPLETION_TIMEOUT ;
			ADD VL_PRESSURE_UNITS,			PARAM.PRESSURE_UNITS ;
			ADD VL_CHARACTERIZATION,		PARAM.CHARACTERIZATION ;
			ADD VL_STROKE_TIME_CLOSE_LIM,		PARAM.STROKE_TIME_CLOSE_LIM ;
			ADD VL_STROKE_TIME_OPEN_LIM,		PARAM.STROKE_TIME_OPEN_LIM ;
			ADD VL_TRAVEL_ACCUM_LIM,		PARAM.TRAVEL_ACCUM_LIM ;
			ADD VL_TRAVEL_ACCUM_UNITS,		PARAM.TRAVEL_ACCUM_UNITS ;
			ADD VL_INTERNAL_TEMP_UNITS,		PARAM.INTERNAL_TEMP_UNITS ;
		}    
	}
    }
}

/********** Resource Block w/ Field Diagnostics ************/

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__RES_BLOCK_2,
		DEVICE_REVISION 	__RES_BLOCK_2_rel_dev_rev,
		DD_REVISION 		__RES_BLOCK_2_rel_dd_rev
{
    EVERYTHING;

    REDEFINITIONS
    {
        BLOCK __resource_block_2
        {
            PARAMETERS
            {
                __FD_PARAMS
                ADD	SOFTWARE_REV,	__software_rev ;
                ADD	HARDWARE_REV,	__hardware_rev ;
            }
        }

        VARIABLE_LIST   __res_2_view_1
        {
            MEMBERS
            {
                __FD_PARAMS_VIEW1
            }    
        }
        
        VARIABLE_LIST   __res_2_view_3
        {
            MEMBERS
            {
                __FD_PARAMS_VIEW3
            }    
        }
        
        VARIABLE_LIST   __res_2_view_4
        {
            MEMBERS
            {
                __FD_PARAMS_VIEW4
            }    
        }
    }
}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__PROG_RES_BLOCK,
		DEVICE_REVISION 	__PROG_RES_BLOCK_beta_dev_rev,
		DD_REVISION 		__PROG_RES_BLOCK_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__GEN_XDCR_BLOCK,
		DEVICE_REVISION 	__GEN_XDCR_BLOCK_beta_dev_rev,
		DD_REVISION 		__GEN_XDCR_BLOCK_beta_dd_rev
{EVERYTHING;}

/*****************************************************************************************************/
/*********************************      Begin Part 3 blocks      *************************************/
/*****************************************************************************************************/

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__ADV_PARAM,
		DEVICE_REVISION 	__ADV_PARAM_rel_dev_rev,
		DD_REVISION 		__ADV_PARAM_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__DEVICE_CONTROL,
		DEVICE_REVISION 	__DEVICE_CONTROL_rel_dev_rev,
		DD_REVISION 		__DEVICE_CONTROL_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__OUTPUT_SPLITTER,
		DEVICE_REVISION 	__OUTPUT_SPLITTER_rel_dev_rev,
		DD_REVISION 		__OUTPUT_SPLITTER_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__SIGNAL_CHARACTERIZER,
		DEVICE_REVISION 	__SIGNAL_CHARACTERIZER_rel_dev_rev,
		DD_REVISION 		__SIGNAL_CHARACTERIZER_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__LEAD_LAG,
		DEVICE_REVISION 	__LEAD_LAG_rel_dev_rev,
		DD_REVISION 		__LEAD_LAG_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__DEADTIME,
		DEVICE_REVISION 	__DEADTIME_rel_dev_rev,
		DD_REVISION 		__DEADTIME_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__INTEGRATOR,
		DEVICE_REVISION 	__INTEGRATOR_rel_dev_rev,
		DD_REVISION 		__INTEGRATOR_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__SETPOINT_RAMP_GENERATOR,
		DEVICE_REVISION 	__SETPOINT_RAMP_GENERATOR_rel_dev_rev,
		DD_REVISION 		__SETPOINT_RAMP_GENERATOR_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__INPUT_SELECTOR,
		DEVICE_REVISION 	__INPUT_SELECTOR_rel_dev_rev,
		DD_REVISION 		__INPUT_SELECTOR_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__ARITHMETIC,
		DEVICE_REVISION 	__ARITHMETIC_rel_dev_rev,
		DD_REVISION 		__ARITHMETIC_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__TIMER,
		DEVICE_REVISION 	__TIMER_rel_dev_rev,
		DD_REVISION 		__TIMER_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__ANALOG_ALARM,
		DEVICE_REVISION 	__ANALOG_ALARM_rel_dev_rev,
		DD_REVISION 		__ANALOG_ALARM_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__CALCULATE_ANALOG,
		DEVICE_REVISION 	__CALCULATE_ANALOG_beta_dev_rev,
		DD_REVISION 		__CALCULATE_ANALOG_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__PULSE_INPUT,
		DEVICE_REVISION 	__PULSE_INPUT_beta_dev_rev,
		DD_REVISION 		__PULSE_INPUT_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__COMPLEX_AO,
		DEVICE_REVISION 	__COMPLEX_AO_beta_dev_rev,
		DD_REVISION 		__COMPLEX_AO_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__COMPLEX_DO,
		DEVICE_REVISION 	__COMPLEX_DO_beta_dev_rev,
		DD_REVISION 		__COMPLEX_DO_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__STEP_OUTPUT_PID,
		DEVICE_REVISION 	__STEP_OUTPUT_PID_beta_dev_rev,
		DD_REVISION 		__STEP_OUTPUT_PID_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__DISCRETE_ALARM,
		DEVICE_REVISION 	__DISCRETE_ALARM_beta_dev_rev,
		DD_REVISION 		__DISCRETE_ALARM_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__ANALOG_HUMAN_INTERFACE,
		DEVICE_REVISION 	__ANALOG_HUMAN_INTERFACE_beta_dev_rev,
		DD_REVISION 		__ANALOG_HUMAN_INTERFACE_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__DISCRETE_HUMAN_INTERFACE,
		DEVICE_REVISION 	__DISCRETE_HUMAN_INTERFACE_beta_dev_rev,
		DD_REVISION 		__DISCRETE_HUMAN_INTERFACE_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__CALCULATE_DISCRETE,
		DEVICE_REVISION 	__CALCULATE_DISCRETE_beta_dev_rev,
		DD_REVISION 		__CALCULATE_DISCRETE_beta_dd_rev
{EVERYTHING;}

/*****************************************************************************************************/
/*********************************      Begin SIF Blocks      ****************************************/
/*****************************************************************************************************/

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		    __SIF_PARM,
		DEVICE_REVISION 	    __SIF_PARM_rel_dev_rev,
		DD_REVISION 		    __SIF_PARM_rel_dd_rev
{EVERYTHING;}  

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		    __SIF_AI_BLOCK,
		DEVICE_REVISION   	    __SIF_AI_BLOCK_rel_dev_rev,
		DD_REVISION 		    __SIF_AI_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		    __SIF_DO_BLOCK,
		DEVICE_REVISION 	    __SIF_DO_BLOCK_rel_dev_rev,
		DD_REVISION 		    __SIF_DO_BLOCK_rel_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		    __SIF_RES_BLOCK,
		DEVICE_REVISION 	    __SIF_RES_BLOCK_rel_dev_rev,
		DD_REVISION 		    __SIF_RES_BLOCK_rel_dd_rev
{EVERYTHING;}


/*****************************************************************************************************/
/*********************************      Begin RIO Blocks      ****************************************/
/*****************************************************************************************************/
IMPORT  MANUFACTURER 		__FF,
		DEVICE_TYPE 		__RIO_PARM,
		DEVICE_REVISION 	__RIO_PARM_beta_dev_rev,
		DD_REVISION 		__RIO_PARM_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER    __FF,
		DEVICE_TYPE     __RIO_ASSOC_PRIMARY_BLOCK,
		DEVICE_REVISION __RIO_ASSOC_PRIMARY_BLOCK_beta_dev_rev,
		DD_REVISION     __RIO_ASSOC_PRIMARY_BLOCK_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER    __FF,
		DEVICE_TYPE     __RIO_ASSOC_BLOCK,
		DEVICE_REVISION __RIO_ASSOC_BLOCK_beta_dev_rev,
		DD_REVISION     __RIO_ASSOC_BLOCK_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER    __FF,
		DEVICE_TYPE     __RIO_MAI16_BLOCK,
		DEVICE_REVISION __RIO_MAI16_BLOCK_beta_dev_rev,
		DD_REVISION     __RIO_MAI16_BLOCK_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER    __FF,
		DEVICE_TYPE     __RIO_MAO16_BLOCK,
		DEVICE_REVISION __RIO_MAO16_BLOCK_beta_dev_rev,
		DD_REVISION     __RIO_MAO16_BLOCK_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER    __FF,
		DEVICE_TYPE     __RIO_MBI64_BLOCK,
		DEVICE_REVISION __RIO_MBI64_BLOCK_beta_dev_rev,
		DD_REVISION     __RIO_MBI64_BLOCK_beta_dd_rev
{EVERYTHING;}

IMPORT  MANUFACTURER    __FF,
		DEVICE_TYPE     __RIO_MBO64_BLOCK,
		DEVICE_REVISION __RIO_MBO64_BLOCK_beta_dev_rev,
		DD_REVISION     __RIO_MBO64_BLOCK_beta_dd_rev
{EVERYTHING;}
