#Automatically generated by ffids.u from definitions in ffids.inc  in FFAP project AND
#manually added to DD-only project
export DEVICE_REV = 03
export DD_REV:=02
export manufacturer_ID:=445644
export DEVICE_TYPE:=0008
export COMPATIBILITY_REVISION:=3
export SW_FF_MINOR:=01


