/* Automatically generated by ffids.u from definitions in ffids.inc in FFAP project AND
manually added to DD-only project
*/
#ifndef FFIDS_H_
#define FFIDS_H_
/*lint ++flb definitions here are mandated ids and may or may not be used
*/
#define UI_FFID "03010000"

#define COMPATIBILITY_REVISION 3
#define MN_MFG_ID_STRING "|en|Masoneilan"
/* Current definition:  RES_VAL_DEV_REV.RES_DEV_MINOR_REV.RES_BUILD.RES_BUILD_REV, thus:
*/
#define SW_APP_DEFAULT_REVISION  0x03010000U
#define SOFTWARE_FF_REVISION  0x03010000U //same as SW_APP_DEFAULT_REVISION
/*Specials for RB:
*/
#define RES_VAL_DEV_TYPE 0x0008U
#define RES_VAL_DEV_REV 0x3
/*This is the *minimum* DD revision compatible with the firmware
*/
#define MIN_DD_REV 1
/*This is the *current* DD revision compatible with the firmware
*/
#define RES_VAL_DD_REV 2
  #define FD_DOM_MFG_ID         "445644"
  #define FD_DOM_MFG_ID_HEX     0x445644
  #define FD_DOM_MFG_ID_NAKED   445644
  #define FD_DOM_FAMILY         "0008"
  #define FD_DOM_DEV_TYPE       "0008"
  #define FD_DEV_TYPE_NAKED     0008
  #define FD_DOM_DEV_REV        3
  #define FD_DOM_DD_REV         2
  #define FD_DOM_SW_REV         "2-42    "
  #define FD_DOM_SW_NAME        "FD-SW   "
  #define FD_DOM_DOM_NAME       "FD-DOM  "

  #define AP_DOM_MFG_ID         FD_DOM_MFG_ID
  #define AP_DOM_FAMILY         FD_DOM_FAMILY
  #define AP_DOM_DEV_TYPE       FD_DOM_DEV_TYPE
  #define AP_DOM_DEV_REV        FD_DOM_DEV_REV
  #define AP_DOM_DD_REV         FD_DOM_DOM_NAME
  #define AP_DOM_SW_REV         FD_DOM_SW_REV
  #define AP_DOM_SW_NAME        "AP-SW   "
  #define AP_DOM_DOM_NAME       "AP-DOM  "

/*lint --flb
*/
#endif //FFIDS_H_

