/*Module HISTOGRAM configuration automatically generated from inc_FFP\HISTOGRAM_config.mak*/
#ifndef HISTOGRAM_CONFIG_H_
#define HISTOGRAM_CONFIG_H_


#define HISTOGRAM_OPTIONS_POSERR_OPTION_WRITABLE (24834 + 2)
#define HISTOGRAM_OPTIONS_POSERR_OPTION_READONLY (24834 + 3)

#define HISTOGRAM_OPTIONS_POSITION_OPTION_WRITABLE (15489 + 2)
#define HISTOGRAM_OPTIONS_POSITION_OPTION_READONLY (15489 + 3)

#define HISTOGRAM_OPTIONS_WORKING_TIMES_OPTION_WRITABLE (30507 + 2)
#define HISTOGRAM_OPTIONS_WORKING_TIMES_OPTION_READONLY (30507 + 3)

#define HISTOGRAM_SELECTION_POSERR (HISTOGRAM_OPTIONS_POSERR_OPTION_READONLY)
#define HISTOGRAM_SELECTION_POSITION (HISTOGRAM_OPTIONS_POSITION_OPTION_WRITABLE)
#define HISTOGRAM_SELECTION_WORKING_TIMES (HISTOGRAM_OPTIONS_WORKING_TIMES_OPTION_READONLY)
#endif /*HISTOGRAM_CONFIG_H_*/
/*End of file*/
