/*Module TBALERTS configuration automatically generated from inc_FFP\TBALERTS_config.mak*/
#ifndef TBALERTS_CONFIG_H_
#define TBALERTS_CONFIG_H_


#define TBALERTS_OPTIONS_CACHE_OPTION_INCLUDE (1452 + 2)
#define TBALERTS_OPTIONS_CACHE_OPTION_EXCLUDE (1452 + 3)

#define TBALERTS_OPTIONS_DEVIATION_CUTOFF_OPTION_IGNORED (12387 + 2)
#define TBALERTS_OPTIONS_DEVIATION_CUTOFF_OPTION_SUSPENDED (12387 + 3)
#define TBALERTS_OPTIONS_DEVIATION_CUTOFF_OPTION_CLEARED (12387 + 4)

#define TBALERTS_OPTIONS_HISTORY_OPTION_INCLUDE (36247 + 2)
#define TBALERTS_OPTIONS_HISTORY_OPTION_EXCLUDE (36247 + 3)

#define TBALERTS_OPTIONS_NEARCLOSED_CUTOFF_OPTION_IGNORED (38651 + 2)
#define TBALERTS_OPTIONS_NEARCLOSED_CUTOFF_OPTION_SUSPENDED (38651 + 3)
#define TBALERTS_OPTIONS_NEARCLOSED_CUTOFF_OPTION_CLEARED (38651 + 4)

#define TBALERTS_SELECTION_CACHE (TBALERTS_OPTIONS_CACHE_OPTION_INCLUDE)
#define TBALERTS_SELECTION_DEVIATION_CUTOFF (TBALERTS_OPTIONS_DEVIATION_CUTOFF_OPTION_SUSPENDED)
#define TBALERTS_SELECTION_HISTORY (TBALERTS_OPTIONS_HISTORY_OPTION_INCLUDE)
#define TBALERTS_SELECTION_NEARCLOSED_CUTOFF (TBALERTS_OPTIONS_NEARCLOSED_CUTOFF_OPTION_SUSPENDED)
#endif /*TBALERTS_CONFIG_H_*/
/*End of file*/
