#MP If 0 ;Tombstone header
/*
Copyright 2020 by Dresser, Inc., as an unpublished trade secret.  All rights reserved.
This document and all information herein are the property of Dresser, Inc.
It and its contents are  confidential and have been provided as a part of
a confidential relationship.  As such, no part of it may be made public,
decompiled, reverse engineered or copied and it is subject to return upon
demand.
*/
/**
    \file common_h_cff.inc
    \brief "Raw materials" for generating artifacts common to .h and .cff files
    Probably, may be expandable over time

    CPU: Any

    OWNER: AK

    \ingroup framework
*/
#MP Endif ;Tombstone header
        #MP
#MP ;Data link pararameters
#MP FF_DLL_min_slot_time = 8
#MP FF_DLL_min_MaxResponseDelay = 3
#MP FF_DLL_MinimumInterPduDelay = 6
#MP
#MP ;NV parameters
#MP FF_NV_CYCLE_T = 5 ;in seconds
